### ISSUE TITLE
Request for the diff_gaussian_rasterization module in submodules

### ISSUE THREAD

**Issue by strawberrrrrry** [jasongzy/MAGS#1]
#### Description
While reviewing the code, I noticed that the `submodules` directory is empty. It seems that the `diff_gaussian_rasterization` module, which is referenced in the code, is missing. Could you please provide the code for this part?

#### Steps to Reproduce
1. Clone the repository.
2. Navigate to the `submodules` directory.
3. Notice that the `diff_gaussian_rasterization` module is not present.

#### Expected Behavior
The `diff_gaussian_rasterization` module should either be included in the `submodules` directory or an alternative solution should be provided to access it.

**Comment by jasongzy** [comment]
You can refer to `.gitmodules` for urls of the submodules.
For example, `diff_gaussian_rasterization` can be cloned from <https://github.com/Zerg-Overmind/diff-gaussian-rasterization>.
